# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbmjxNLbNsqdUYTsSu-QgDouq3pc6I3D
"""

import os
from flask import Flask, render_template, request, jsonify
from openai import OpenAI

app = Flask(__name__)

# No servidor web (Render) ou no seu computador, pegamos a chave das Variáveis de Ambiente
# Isso substitui o userdata.get() do Google Colab
CHAVE_API = os.environ.get('OPENROUTER_API_KEY')

# Instancia o cliente apontando para a OpenRouter
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=CHAVE_API
)

# Definir o modelo a ser utilizado
MODELO = "nousresearch/hermes-3-llama-3.1-405b"

@app.route("/")
def index():
    # Carrega a interface visual
    return render_template("index.html")

@app.route("/chat", methods=["POST"])
def chat():
    dados = request.json
    pergunta = dados.get("message")

    if not pergunta:
        return jsonify({"error": "Nenhuma pergunta recebida."}), 400

    try:
        # Aqui substituímos o seu input() pela chamada da API
       response = client.chat.completions.create(
            model="nousresearch/hermes-3-llama-3.1-405b",
            messages=[
                {"role": "system", "content": "Você é um assistente virtual útil e amigável. Você deve responder SEMPRE em português do Brasil."},
                {"role": "user", "content": user_message}
            ]
        )

        # Extrai o texto da resposta da IA
        texto_resposta = resposta.choices[0].message.content
        return jsonify({"reply": texto_resposta})

    except Exception as e:
        return jsonify({"error": f"Erro na IA: {str(e)}"}), 500

if __name__ == "__main__":
    app.run(debug=True)
